version: '3'
services:
  reverseproxy:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/wildcard.companieshouse.gov.uk.crt:/etc/nginx/wildcard.companieshouse.gov.uk.crt
      - ./nginx/wildcard.companieshouse.gov.uk.key:/etc/nginx/wildcard.companieshouse.gov.uk.key
    ports:
      - 80:80
      - 443:443
    restart: always

  ewf-ig:
    depends_on:
      - reverseproxy
    environment:
      - APPLICATION_HOST=${APPLICATION_HOST}
      - APPLICATION_LEGACY_HOST=${APPLICATION_LEGACY_HOST}
      - IG_HOST=${IG_HOST}
      - APPLICATION_LEGACY_HOST_PREFIX=${APPLICATION_LEGACY_HOST_PREFIX}
      - APPLICATION_HOST_PREFIX=${APPLICATION_HOST_PREFIX}
      - FIDC_FQDN=${FIDC_FQDN}
      - FIDC_REALM=${FIDC_REALM}
      - FIDC_LOGIN_JOURNEY=${FIDC_LOGIN_JOURNEY}
      - FIDC_MAIN_JOURNEY=${FIDC_MAIN_JOURNEY}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - UI_URL=${UI_URL}
      - LOGIN_PATH=${LOGIN_PATH}
      - ERROR_PATH=${ERROR_PATH}
    build:
      context: ./webfiling
      args:
        DOCKER_IMAGE: ${DOCKER_IMAGE}
  
  chs-ig:
    depends_on:
      - reverseproxy
    environment:
      - API_LOAD_BALANCER=${API_LOAD_BALANCER}
    build:
      context: ./chs
      args:
        DOCKER_IMAGE: ${DOCKER_IMAGE}
